CC = mpicc

all: pa1a pa1b pa1c
.PHONY : all
	
clean:
	rm pa1a pa1b pa1c
.PHONY : clean

pa1a: pa1a.c
	$(CC) -g -Wall -o pa1a $@.c 
.PHONY : pa1a

pa1b: pa1b.c
	$(CC) -g -Wall -o pa1b $@.c
.PHONY : pa1b

pa1c: pa1c.c
	$(CC) -g -Wall -o pa1c $@.c
.PHONY : pa1c